// KillZone account controls v3 — uses the app's global lexical currentUser correctly.
(function(){
  'use strict';
  let overlay=null, busy=false;
  const esc=v=>typeof escapeHtml==='function'?escapeHtml(v):String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  function styles(){
    if(document.getElementById('kzAccountFix3'))return;
    const s=document.createElement('style');s.id='kzAccountFix3';s.textContent='.kz-profile-modal{max-width:620px!important}.kz-profile-danger{margin-top:18px;padding-top:18px;border-top:1px solid var(--line)}.kz-danger{border:1px solid #9b3d2c!important;color:#ffb3a5!important}.kz-profile-warning{padding:12px;border:1px solid #9b3d2c;background:rgba(155,61,44,.12);line-height:1.8}';document.head.appendChild(s);
  }
  function close(){if(overlay){overlay.remove();overlay=null;}}
  function open(){if(!currentUser)return;styles();close();const u=currentUser;overlay=document.createElement('div');overlay.className='overlay show';overlay.innerHTML=`<div class="modal kz-profile-modal"><button class="close" id="kzP3Close">✕</button><h3>تنظیمات اکانت</h3><div class="form-grid"><div class="field"><label>نام‌کاربری</label><input value="${esc(u.username)}" disabled></div><div class="field"><label>رنک</label><input value="${esc(typeof rankLabel==='function'?rankLabel(u.rank):u.rank)}" disabled></div><div class="field"><label>بازی‌های مورد علاقه</label><input id="kzP3Game" value="${esc(u.game||'')}" maxlength="200"></div><div class="field"><label>عکس پروفایل جدید</label><input id="kzP3Photo" type="file" accept="image/*"></div><div class="field"><label>رمز عبور جدید</label><input id="kzP3Pass" type="password" minlength="4" maxlength="60" placeholder="اختیاری"></div><button class="btn primary" id="kzP3Save">ذخیره تغییرات</button><div id="kzP3Msg"></div></div><div class="kz-profile-danger"><strong>حذف اکانت</strong><p>اکانت، درخواست‌های عضویت و پیام‌های خودت برای همیشه حذف می‌شن.</p><button class="btn kz-danger" id="kzP3Delete">حذف دائمی اکانت</button></div></div>`;document.body.appendChild(overlay);document.getElementById('kzP3Close').onclick=close;document.getElementById('kzP3Save').onclick=save;document.getElementById('kzP3Delete').onclick=del;}
  function msg(t,ok){const e=document.getElementById('kzP3Msg');if(e)e.innerHTML=`<div class="form-msg ${ok?'ok':'err'}">${esc(t)}</div>`;}
  async function save(){if(busy||!currentUser)return;busy=true;try{const up={game:(document.getElementById('kzP3Game').value||'').trim()};const f=document.getElementById('kzP3Photo').files?.[0];if(f&&typeof uploadPhoto==='function'){const url=await uploadPhoto(f,()=>{});if(url)up.photo=url;}const p=document.getElementById('kzP3Pass').value;if(p){if(p.length<4)throw Error('رمز جدید باید حداقل ۴ کاراکتر باشد.');up.pass_hash=await hashPass(p);}const {data,error}=await sb.from('accounts').update(up).eq('id',currentUser.id).select('*').maybeSingle();if(error||!data)throw error||Error('اجازه ویرایش اکانت وجود ندارد.');currentUser=data;saveSession(data);if(typeof renderUserBox==='function')renderUserBox();msg('تغییرات ذخیره شد ✔',true);setTimeout(close,700);}catch(e){console.error(e);msg(e.message||'ذخیره ناموفق بود.',false);}finally{busy=false;}}
  async function del(){if(busy||!currentUser)return;const u=currentUser;if(prompt(`برای حذف «${u.username}»، نام‌کاربری را دقیقاً وارد کن:`)!==u.username)return;if(!confirm('این عملیات قابل برگشت نیست. ادامه می‌دی؟'))return;busy=true;try{await sb.from('team_join_messages').delete().eq('account_id',u.id);await sb.from('team_join_requests').delete().eq('account_id',u.id);const {error}=await sb.from('accounts').delete().eq('id',u.id);if(error)throw error;clearSession();currentUser=null;close();location.href='index.html';}catch(e){console.error(e);alert('حذف اکانت ناموفق بود. اگر خطای RLS داری، policyهای Supabase باید اصلاح شوند.');}finally{busy=false;}}
  function add(){if(!currentUser)return;const box=document.getElementById('userBox');if(!box||box.querySelector('#kzP3Btn'))return;const b=document.createElement('button');b.id='kzP3Btn';b.className='link-btn';b.textContent='⚙️ اکانت';b.onclick=open;const out=box.querySelector('#logoutBtn');if(out)box.insertBefore(b,out);else box.appendChild(b);}
  function patch(){if(typeof renderUserBox!=='function'||renderUserBox.__kzP3)return;const orig=renderUserBox;const w=function(){orig();add();};w.__kzP3=true;window.renderUserBox=w;}
  function reg(){if(typeof registerUser!=='function'||registerUser.__kzP3)return;const orig=registerUser;const w=async function(...args){const r=await orig(...args);if(r?.ok&&r.account?.id){const q=await sb.from('accounts').update({rank:'member',team_status:'none'}).eq('id',r.account.id).select('*').maybeSingle();if(q.data)r.account=q.data;}return r;};w.__kzP3=true;window.registerUser=w;}
  function boot(){styles();patch();reg();setTimeout(()=>{if(typeof initSession==='function')initSession().then(()=>{if(typeof renderUserBox==='function')renderUserBox();});},0);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
